version: '3.5'

services:
  app:
    build:
      context: '.'
      args:
        uid: 1000
    container_name: app
    restart: always
    ports:
      - 8888:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ./:/var/www/html
